// src/App.tsx
import "./styles.css";
import { useEffect, useState } from "react";

interface TableData {
  name: string;
  gender: string;
  email: string;
  phone: string;
  location: string;
}

interface Header {
  value: string;
  sortedUp: boolean;
}

export default function App() {
  const [headers, setHeaders] = useState<Header[]>([
    { value: "name", sortedUp: true },
    { value: "gender", sortedUp: true },
    { value: "email", sortedUp: true },
    { value: "phone", sortedUp: true },
    { value: "location", sortedUp: true },
  ]);
  const [tableData, setTableData] = useState<TableData[]>([]);

  const getUserData = async () =>
    await fetch("https://randomuser.me/api/?results=30")
      .then((response) => response.json())
      .then((data) => data.results)
      .catch((error) => console.log(error));

  const mapDataToTable = (data: any[]) => {
    setTableData(
      data.map((element) => ({
        name: `${element.name.first} ${element.name.last}`,
        gender: element.gender,
        email: element.email,
        phone: element.phone,
        location: `${element.location.city}, ${element.location.country}`,
      }))
    );
  };

  const sortTableBy = (header: Header) => {
    const headerType = header.value as keyof TableData;
    setTableData(
      tableData.sort((a, b) =>
        header.sortedUp
          ? b[headerType].localeCompare(a[headerType])
          : a[headerType].localeCompare(b[headerType])
      )
    );
    setHeaders(
      headers.map((h) =>
        h.value === header.value
          ? { ...h, sortedUp: !header.sortedUp }
          : { ...h, sortedUp: true }
      )
    );
  };

  useEffect(() => {
    getUserData().then(mapDataToTable);
  }, []);

  return (
    <table>
      <thead>
        <tr>
          {headers.map((header, index) => (
            <th key={index} className="table__header">
              {header.value}
              <button
                className={`table__header-button ${
                  !header.sortedUp ? "table__header-button--down" : ""
                }`}
                onClick={() => sortTableBy(header)}
              >
                ⬆️
              </button>
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {tableData.map((row, index) => (
          <tr key={index}>
            {Object.values(row).map((col, index) => (
              <td className="table__data" key={index}>
                {col}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

interface TableData {
  name: string;
  gender: string;
  email: string;
  phone: string;
  location: string;
}

interface Header {
  value: string;
  sortedUp: boolean;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  headers: Header[] = [
    { value: 'name', sortedUp: true },
    { value: 'gender', sortedUp: true },
    { value: 'email', sortedUp: true },
    { value: 'phone', sortedUp: true },
    { value: 'location', sortedUp: true },
  ];
  tableData: TableData[] = [];

  ngOnInit() {
    this.getUserData().then(this.mapDataToTable);
  }

  async getUserData() {
    return await fetch('https://randomuser.me/api/?results=30')
      .then((response) => response.json())
      .then((data) => data.results)
      .catch((error) => console.log(error));
  }

  mapDataToTable = (data: any) => {
    this.tableData = data.map((entry: any) => ({
      name: `${entry.name.first} ${entry.name.last}`,
      gender: entry.gender,
      email: entry.email,
      phone: entry.phone,
      location: `${entry.location.city}, ${entry.location.country}`,
    }));
  };

  sortTableBy = (header: Header) => {
    const headerType = header.value as keyof TableData;
    this.tableData.sort((a, b) =>
      header.sortedUp
        ? b[headerType].localeCompare(a[headerType])
        : a[headerType].localeCompare(b[headerType])
    );
    this.headers = this.headers.map((element) =>
      element.value === header.value
        ? { ...element, sortedUp: !header.sortedUp }
        : { ...element, sortedUp: true }
    );
  };
}

<table>
  <thead>
    <tr>
      <th *ngFor="let header of headers">
        {{ header.value }}
        <button
          class="header__button"
          [ngClass]="{ 'header__button--down': !header.sortedUp }"
          (click)="sortTableBy(header)"
        >
          ⬆️
        </button>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let row of tableData">
      <td>{{ row.name }}</td>
      <td>{{ row.gender }}</td>
      <td>{{ row.email }}</td>
      <td>{{ row.phone }}</td>
      <td>{{ row.location }}</td>
    </tr>
  </tbody>
</table>
