// src/app/components/todo-item/todo-item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent {
  @Input() label = '';
  @Output() onDelete = new EventEmitter<void>();
  itemChecked = false;
}
<div>
    <input type="checkbox" [(ngModel)]="itemChecked"/>
    <span [class]="{'checked': itemChecked}"> {{ label }} </span> 
    <button (click)="onDelete.emit()">x</button>
</div>

// my-app/src/components/TodoItem/TodoItem.tsx
import TrashIcon from "../../assets/TrashIcon";
import "./TodoItem.css";

type TodoItemProps = {
  label: string;
  checked: boolean;
  onCheck: () => void;
  onDelete: () => void;
};

const TodoItem = ({ label, checked, onCheck, onDelete }: TodoItemProps) => {
  return (
    <div className="todo-item__wrapper">
      <>
        <input type="checkbox" onChange={onCheck} checked={checked} />
        <span style={checked ? { textDecoration: "line-through" } : {}}>
          {label}
        </span>
        <button onClick={onDelete}>
          <TrashIcon />
        </button>
      </>
    </div>
  );
};

export default TodoItem;
